### ISSUE TITLE
Connection Issue on MSSQL

### ISSUE THREAD

**Issue by ashtonfei** [ebarreat/Google-Spreadsheet-JDBC#2]
Hi Ebarreat,

With the help of your code, I finally made my script working perfectly on MySQL server. But it can not connect to MSSQL server with this URL formula. 

`dbUrl = 'jdbc:sqlserver://' + address + ':1433;databaseName=' + queryDb;`

**Comment by ebarreat** [comment]
You will have to make sure that the Windows Server has that port (1433 )  allowing traffic. Also make sure the user has the correct permissions. Sorry for the late reply!

**Comment by ebarreat** [comment]
```
  var address;
  var user;
  var userPwd ;
  var dbUrl;
  var queryDb = 'MyMain_Db';
  address = 'my.address.net';
  user = 'MYUSER';
  userPwd = 'MYSTRONGPASSWORD';
  dbUrl = 'jdbc:sqlserver://' + address + ':1433;databaseName=' + queryDb;
  var conn = Jdbc.getConnection(dbUrl, user, userPwd);
```


You will also let the Window's server allow GOOGLE's IP's. This is very important. Let me know if that helps!  You can find more JDBC Service Help from google [HERE!](https://developers.google.com/apps-script/guides/jdbc)

IPS:
```
64.18.0.0 - 64.18.15.255
64.233.160.0 - 64.233.191.255
66.102.0.0 - 66.102.15.255
66.249.80.0 - 66.249.95.255
72.14.192.0 - 72.14.255.255
74.125.0.0 - 74.125.255.255
173.194.0.0 - 173.194.255.255
207.126.144.0 - 207.126.159.255
209.85.128.0 - 209.85.255.255
216.239.32.0 - 216.239.63.255
```
